services:
  ui:
    build:
      context: ./ui
    container_name: wdmmg-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    env_file: .env

  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
